version: '3.1'

services:

  api:
    build: ./api
    restart: always
    depends_on:
      - postgres
      - migrator
    ports:
      - '3000:3000'
    environment:
      APP_PORT: 3000
      LOG_FILE: ./logs.txt
      LOG_NAME: cars_api
      LOG_LEVEL: debug

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: nestcars


  migrator:
    build: ./migrator
    depends_on:
      - postgres

  postgres:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: nestcars
    ports:
    - 15432:5432
    volumes:
    - postgress:/var/lib/postgresql/data

volumes:
  postgress:
