version: '3.1'

services:

  postgres:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: nestcars
    ports:
    - 15432:5432
    volumes:
    - postgress:/var/lib/postgresql/data

volumes:
  postgress:
