export const CONFIG_NAMES = [
  'APP_PORT',
  'LOG_FILE',
  'APP_LOG_LABEL',
  'APP_LOG_LEVEL',
  'POSTGRES_HOST',
  'POSTGRES_PORT',
  'POSTGRES_USER',
  'POSTGRES_PASSWORD',
  'POSTGRES_DATABASE',
]
